### ISSUE TITLE
Unable to use require() on 'it-pipe' package

### ISSUE THREAD

**Issue by ShubhGohil** [alanshaw/it-pipe#12]
I am working with on a project based on ipfs and using js-ipfs for the same. While using the ipfs.get() API, I need to use pipe function. I am not working with ES modules, so **do not want to use import keyword** on **'it-pipe'** package, instead **want to use require()**. I am using 2.0.3 version.

I am unable to use 
```sh
const { pipe } = require('it-pipe')
```
It throws the following error,
```sh
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/shubh/Desktop/BTech/Project/decentralizedwebhosting/DWH/server/node_modules/it-pipe/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:645:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/shubh/Desktop/BTech/Project/decentralizedwebhosting/DWH/server/src/ipfs.js:11:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I did not understand what the error I trying to say, from " No "exports" main defined ". I tried changing some values in the package.json file of the 'it-pipe' package, but failed to get any result or reason for the error.

Here is the code where I want to use pipe,
```js
    async function * tarballed (source) {
        yield * pipe(
            source,
            extract(),
            async function * (source) {
                for await (const entry of source) {
                    yield {
                        ...entry,
                        body: await toBuffer(map(entry.body, (buf) => buf.slice()))
                    }
                }
            }
        )
    }
    
    async function collect (source) {
        return all(source)
    }

    const output = await pipe(
        ipfs.get(cid),
        tarballed,
        collect
    )
    
    const paths = output.map((file) => { console.log(uint8arraysToString(file.body)) });
```
This code is taken from from the official [js-ipfs](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/get.js) testing code. The pipe function is used on line 86 and line 219.

**Please help me on how to use 'it-pipe' package in commonjs form and use functions of 'it-pipe' package using require keyword.**

**Comment by vincekinyops** [comment]
my problem is there's no "default" export on some of the modules

**Comment by achingbrain** [comment]
`it-pipe@v2` is an ESM-only module, so you can only `import` it, you cannot `require` it.

If your project only uses CJS and cannot upgrade, please use `it-pipe@v1` which was CJS and can be used with `require`.
