### ISSUE TITLE
Potential ts-ignore effect in current type definition

### ISSUE THREAD

**Issue by dapplion** [alanshaw/it-pipe#4]
Current type definitions compile fine with invalid arguments such as
```ts
await pipe(1, "e", 0, null)
```

This can be an issue for strongly typed projects since Typescript won't notify of type issues within it-pipe arguments. Seems that the issue comes from this overload

https://github.com/alanshaw/it-pipe/blob/825195720c72bf40c08335223bfa40ae2624d150/index.d.ts#L82

if the pipe argument types are invalid and don't satisfy any of the above well-crafted types line 82 acts as a sort of `@ts-ignore`.

While this final overload allows for relaxed usage it's a strong cause of concern for Typescript consumers

CC: @mpetrunic @wemeetagain

**Comment by mpetrunic** [comment]
Yeah notifced it before. But if you remove it, ts projects using more than 10 functions in pipe will fail. 
We could try something like this. Seems like similar example:
https://stackoverflow.com/questions/53173203/typescript-recursive-function-composition

**Comment by dapplion** [comment]
> Yeah notifced it before. But if you remove it, ts projects using more than 10 functions in pipe will fail.
> We could try something like this. Seems like similar example:
> https://stackoverflow.com/questions/53173203/typescript-recursive-function-composition

For the record, lib.es2015.promise.d.ts types for Promise.all overload up to 10 arguments, and if you use more it just doesn't compile.

Tho the example you linked is interesting

**Comment by mpetrunic** [comment]
Also typescript 4.1 introduces recursive types: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#recursive-conditional-types

**Comment by dapplion** [comment]
> Also typescript 4.1 introduces recursive types: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#recursive-conditional-types

Do you think they can provide a solution here? Check this note in the Typescript docs itself
> But apart from being computationally intensive, these types can hit an internal recursion depth limit on sufficiently-complex inputs. When that recursion limit is hit, that results in a compile-time error. In general, it’s better not to use these types at all than to write something that fails on more realistic examples.

Also, if you are piping more than 10 arguments at once it may indicate the code should be simplified

**Comment by mpetrunic** [comment]
> Do you think they can provide a solution here? Check this note in the Typescript docs itself

No idea.
 
> Also, if you are piping more than 10 arguments at once it may indicate the code should be simplified

Don't think so, I mean having
```
pipe(
   sanitize,
   encode,
   compress,
   chunkify
   send,
   collect,
   decompress,
   decode
)
```
is a lot more expressive then:
```
pipe(prepareData, send, collectAndDecode)
```
Probably more performant as well.

**Comment by achingbrain** [comment]
As of `v2` this module has proper types so this now errors as expected:

```
test/index.spec.ts:132:16 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'Source<unknown>'.

132     await pipe(1, "e", 0, null)
```

The cause was the `export function pipe (first: any, ...rest: any[]): any ` definition - tsc was choosing it over the other overloads which meant everything was any.  That definition is no longer exported which gives you type safety but limits the number of piped args to the number of overloads - currently 10.

This isn't ideal but I couldn't figure out a nice way of getting the types to reflect the fact that the `pipe` function has an arbitrary number of arguments, that the output of one is the input into the next, and that the output of the last is the return type of the `pipe` function.  I would happily merge a PR that improves things!

**Comment by dapplion** [comment]
Thanks! I think 10 is plenty
